[package]
name = "nodara_sdk"
version = "1.0.0"
authors = ["Votre Nom <votre.email@example.com>"]
edition = "2021"
description = "JavaScript/TypeScript SDK for interacting with Nodara BIOSPHÈRE QUANTIC."

[lib]
path = "src/lib.rs"
