name: CI/CD Pipeline for Nodara BIOSPHÈRE QUANTIC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build, Test & Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - name: Cache Cargo Registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo Git
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}

      - name: Build Project in Release Mode
        run: cargo build --release

      - name: Run All Tests
        run: cargo test --all --verbose

      - name: Run Benchmarks
        if: github.event_name == 'push'
        run: cargo bench --features runtime-benchmarks

  deploy:
    name: Deploy to Testnet
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Testnet
        run: |
          echo "Deploying to testnet..."
          chmod +x ./deployment_and_operations/deploy.sh
          ./deployment_and_operations/deploy.sh
